import React from 'react';
import Tabs from '@material-ui/core/Tabs';
import Tab from '@material-ui/core/Tab';
import { NavigationTabsTypes } from './NavigationTabs.props';

/**
 * ToDoNavigationTabs is generated by Webcodesk. Replace this comment with a valuable description.
 */
class NavigationTabs extends React.Component {
  constructor(props) {
    super(props);
  }

  handleChangeTab = (event, value) => {
    if (this.props.onChangeActiveTab) {
      this.props.onChangeActiveTab({tabType: value});
    }
  };

  render() {
    const { activeTabType, tabs } = this.props;
    const tabsContent = [];
    for (let i = 0; i < tabs.length; i++){
      tabsContent.push(
        <Tab key={`tabItem${i}`} label={tabs[i].tabLabel} value={tabs[i].tabType} />
      );
    }
    return (
      <Tabs
        value={activeTabType}
        onChange={this.handleChangeTab}
        indicatorColor="primary"
        textColor="primary"
        centered
      >
        {tabsContent}
      </Tabs>
    );
  }
}

NavigationTabs.propTypes = NavigationTabsTypes;

NavigationTabs.defaultProps = {
  activeTabType: 'all',
  tabs: [
    {tabType: 'all', tabLabel: 'All'},
    {tabType: 'active', tabLabel: 'Active'},
    {tabType: 'completed', tabLabel: 'Completed'},
  ]
};

export default NavigationTabs;
