/**
 * This function is generated by Webcodesk. Replace this comment with a valuable description.
 * Don't forget to describe outputs and their compatibility with other functions or components.
 */
export const setActiveNavigationTab = (
  options,
  { stateByDispatch, history }
) => dispatch => {
  if (stateByDispatch && options) {
    const { tabType } = options;
    const { props } = stateByDispatch;
    const newProps = {...props, ...{activeTabType: tabType}};
    dispatch({ props:  newProps});
  }
};
