/**
 * This function is generated by Webcodesk. Replace this comment with a valuable description.
 * Don't forget to describe outputs and their compatibility with other functions or components.
 */
export const goToUrl = (
  options,
  { history }
) => dispatch => {
  if (options && history) {
    const { href } = options;
    if (href) {
      history.push(href);
    }
  }
};
