import React from 'react';
import { PageRouteAnchorTypes } from './PageRouteAnchor.props';

/**
 * PageRouteAnchor is generated by Webcodesk. Replace this comment with a valuable description.
 */
const PageRouteAnchor = () => {
  return null;
};

PageRouteAnchor.propTypes = PageRouteAnchorTypes;

PageRouteAnchor.defaultProps = {
};

export default PageRouteAnchor;
