/**
 * This function is generated by Webcodesk. Replace this comment with a valuable description.
 *
 * @functionTypes {SetActiveTopNavigationByUrlTypes from ./props/TopNavigation.props.js}
 */
export const setActiveTopNavigationByUrl = ({url}, state) => dispatch => {
  console.info('State: ', state);
  if (url && state) {
    // decompose targets states by connected dispatches
    const { properties: targetState } = state;
    if (targetState) {
      // decompose target state by connected props
      // it lets us to check if the user connected a function dispatch to the appropriate prop in the component instance
      const { properties: connectedPropState } = targetState;
      if (connectedPropState) {
        const topNavigationItems = connectedPropState.items;
        if (topNavigationItems && topNavigationItems.length > 0) {
          for (let i = 0; i < topNavigationItems.length; i++) {
            topNavigationItems[i].active = topNavigationItems[i].url === url;
          }
        }
        dispatch({properties: connectedPropState});
      }
    }
  }
};
